### ISSUE TITLE
how to setup path-style requests with custom endpoint?

### ISSUE THREAD

**Issue by hradec** [aws-amplify/aws-sdk-ios-spm#103]
I'm trying to upload data to a custom s3 bucket (currently s3ninja hosted on a custom server) using AWSS3TransferUtility.s3TransferUtility(), but the requests are being done using virtual-hosted–style (where the bucket name is a subdomain of the endpoint domain) instead of simple path-style. 

Is there a way to force it to use path-style requests?

**Comment by hradec** [comment]
should this be on [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios) instead of here?

**Comment by thisisabhash** [comment]
You're right - closing this in lieu of https://github.com/aws-amplify/aws-sdk-ios/issues/5023
