### ISSUE TITLE
Apple Privacy manifest Requirement

### ISSUE THREAD

**Issue by mejim707** [aws-amplify/aws-sdk-ios-spm#112]
Hi, will you have an updated version which supports Apples new Privacy Manifest requirement? This is necessary as Apple will reject any app which use SDKs that do not include the Privacy Manifest. This requirement goes into effect in April of 2024 which is fast coming. 

If you have a version with this Privacy Manifest, can you please provide details?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

Thanks

**Comment by ruisebas** [comment]
This has been released in version [**2.34.2**](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.34.2).
Closing
