### ISSUE TITLE
Package.resolved pin keeps changing

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/aws-sdk-ios-spm#50]
Hi, I noticed that the record for AWSiOSSDKV2 keeps changing. I'm trying to figure out if the change is caused by different xcode 13 versions, but basically, jenkins nodes tend to remove it when building
![image](https://user-images.githubusercontent.com/5980943/158564620-920f1cf2-67da-4ac8-a7f3-ed95a9e1c4bc.png)

And dev machines try to add it back

![image](https://user-images.githubusercontent.com/5980943/158564455-57246d11-3ace-464e-8a02-5561cf99d1d0.png)

Builds keep failing due to git being dirty.
One info that might be useful is that I'm using `https://github.com/awslabs/aws-mobile-appsync-sdk-ios` on local swift package module.

**Comment by atierian** [comment]
Thanks for opening this issue @gevartosky. We'll take a look at this and get back to you.

**Comment by atierian** [comment]
It seems that this is a general Xcode / SPM issue that can occur when your app depends on the same dependency through multiple channels; either direct + transitively, or multiple transitive. In that case, if the URLs aren't identical, this issue can happen. So if one has `.git` and the other doesn't or if one uses SSH and the other HTTPS.

```mermaid
flowchart LR
App --> FooKit
App -->|https://github.com/foo/bar| BarKit
FooKit -->|https://github.com/foo/bar.git| BarKit
```
```mermaid
flowchart LR
App --> FooKit
App --> BarKit
FooKit -->|https://github.com/foo/baz| BazKit
BarKit -->|https://github.com/foo/baz.git| BazKit
```

Based on your info about using AWSAppSync, I believe that may be the case here.
If you're depending on AWS SDK iOS either directly or through another dependency (Amplify for example), can you check that the URLs in the applicable `Package.swift` files are identical?

Please let us know whether this fixes your issue or not. Thanks!

**Comment by gevartosky** [comment]
Thanks for the detailed answer @atierian. I noticed these days that our devs were using different versions of xcode. I asked everyone to update xcode 13.3 and the issue stopped

**Comment by atierian** [comment]
Great! I'm going to close this issue now then.
