### ISSUE TITLE
Warning from Xcode when it's uploaded to App Store

### ISSUE THREAD

**Issue by julioarregoitia** [aws-amplify/aws-sdk-ios-spm#68]
We have an issue(a warning to be more clear) with the latest version(2.28.0) of AWSiOSSDKV2 at the moment of the upload to App Store. You can see in the next picture the warning

![Captura de Pantalla 2022-09-21 a la(s) 1 09 22 a m](https://user-images.githubusercontent.com/35386842/191419874-88d34128-6975-446b-9fe0-7f0325d349b9.png)

**Comment by atierian** [comment]
Thanks for opening this @julioarregoitia. We're aware of this issue and tracking it here https://github.com/aws-amplify/aws-sdk-ios/issues/4314, so I'm going to close this issue as a duplicate. So far all reports indicate that the distribution to AppStoreConnect succeeds. If that's not the case for you, please comment on the linked issue. Thanks!
