### ISSUE TITLE
AWSiOSSDKV2 prevents the use of SwiftUI Previews in Xcode 14

### ISSUE THREAD

**Issue by dlewandaDK** [aws-amplify/aws-sdk-ios-spm#71]
Our project has been using AWSiOSSDKV2 for quite some time, currently pinned to 2.27.9. Once we upgraded to Xcode 14, we are no longer able to use SwiftUI Previews that previously worked in Xcode 13.4.1. This appears to be [an issue](https://developer.apple.com/forums/thread/707569?answerId=731403022&replyId=731403022&login=true) across multiple third party libraries but other libraries are [making fixes to address the issue](https://github.com/microsoft/appcenter-sdk-apple/pull/2433), so I was hoping that the AWSiOSSDKv2 team would consider making a similar change to restore the ability for those of us using this library to also use previews.

The error we're encountering is as follows:
```HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x00006000a6784f90):'AWSCore'>)```
```

The steps to reproduce are to depend on this package and then try to open a SwiftUI View that previously was preview-able in the earlier version of Xcode.

Please note that we tried upgrading to **2.28.0** but still encountered the same problem.

**Comment by sameer4** [comment]
we Have the same problem.

**Comment by atierian** [comment]
Thanks for letting us know @dlewandaDK. If you experience this issue with future Xcode versions, please let us know and we'll take a look.
