### ISSUE TITLE
Tag 2.29.1 disappeared

### ISSUE THREAD

**Issue by iosdevben** [aws-amplify/aws-sdk-ios-spm#85]
Our builds started failing because it appears that tag 2.29.1 has been deleted.

**Comment by psoto-dev** [comment]
We are having the same issue with 2.28.6

**Comment by n1ac-pge** [comment]
We are having the same issue with v2.29.1

**Comment by royjit** [comment]
Apologies for the inconvenience, tag v2.29.1 might have been deprecated. Please use the latest version from this repo.
