### ISSUE TITLE
Checking Status of this Repo

### ISSUE THREAD

**Issue by afern247** [aws-amplify/aws-sdk-ios-spm#89]
Is this repo still active? Is this still the way to communicate with things like Lambda functions and push notifications?

**Comment by royjit** [comment]
Hi @afern247,

Sole purpose of this repo is to provide SPM support for the repo [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios).
Please use the below destination to submit features/bugs:
 AWS SDK for iOS - https://github.com/aws-amplify/aws-sdk-ios
Amplify for Swift - https://github.com/aws-amplify/amplify-swift
